/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Varad' at '9/1/15 3:00 PM' with Gradle 2.4
 *
 * @author Varad, @date 9/1/15 3:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
